language: node.js
node_js: node
sudo: required
cache:
  directories:
    - "node_modules"
before_install:
  - cd $TRAVIS_BUILD_DIR/client
  - docker build -f Dockerfile.dev -t wildanazz/client .
script:
  - docker run -e CI=true wildanazz/client yarn run test --coverage