version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules